import { ICategory } from "@/types/constantsTypes";

export const NEW: string[] = [
  "Glitch Effect",
  "Neon Borders",
  "Swipe Reveal",
  "Sticky Hover",
  "Hover Magnet",
  "Flow Particles",
  "Dynamic Ribbons",
  "Morphing Shapes",
  "Wavy Gallery",
  "Perspective Carousel",
  "Speed Tracker",
  "Rolling Counter",
  "Pulse Glow",
];
export const UPDATED: string[] = [
  "Shatter Effect",
  "Glass Morphism",
  "Typewriter",
  "Scroll Parallax",
  "Pixel Morph",
  "Float Cards",
  "Wave Distortion",
];

export const CATEGORIES: ICategory[] = [
  {
    name: "Text Animations",
    elements: [
      "Glitch Effect",
      "Neon Borders",
      "Typewriter",
      "Swipe Reveal",
      "Distorted Text",
      "Text Gradient",
      "Flicker Text",
      "Ghost Typing",
      "Scroll Fade",
      "Perspective Text",
      "Scroll Magnet",
      "Bounce Letters",
      "Proximity Glow",
      "Typing Effect",
    ],
  },
  {
    name: "Layout Animations",
    elements: [
      "Sticky Hover",
      "Hover Magnet",
      "Rolling Counter",
      "Expanding Card",
      "Morphing Modal",
      "Snap Scroll",
      "Rotating List",
      "Collapsible Section",
      "Gradient Toolbar",
      "Step Progress",
      "Elastic Drawer",
      "Wavy Menu",
      "Glow Navigation",
      "Bouncing Grid",
    ],
  },
  {
    name: "Data Visualization",
    elements: [
      "Flow Particles",
      "Dynamic Ribbons",
      "Wave Distortion",
      "Electric Grid",
      "Speed Tracker",
      "Galaxy Particles",
      "Plasma Motion",
      "Flow Fields",
      "Psychedelic Waves",
      "Hyper Glow",
      "Noise Pattern",
      "Hexa Grid",
      "Futuristic Blur",
    ],
  },
  {
    name: "Interactive Components",
    elements: [
      "Morphing Shapes",
      "Wavy Gallery",
      "Perspective Carousel",
      "Shatter Effect",
      "Glass Morphism",
      "Pixel Morph",
      "Float Cards",
      "Hover Warp",
      "Cursor Trail",
      "Image Overlay",
      "Shimmer Border",
      "Blurred Motion",
      "Random Pulse",
      "Infinite Wipe",
    ],
  },
];
